version: '3'
services:
  app:
    container_name: friend_app
    build: .
    ports:
      - 8081:8081
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - fullstack-mysql
    networks:
      - fullstack

  fullstack-mysql:
    image: mysql:latest
    container_name: friend_db_mysql
    ports:
      - 33061:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=golang
    volumes:
      - database_mysql:/var/lib/mysql
      - ./db_migration:/docker-entrypoint-initdb.d
    networks:
      - fullstack

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    depends_on:
      - fullstack-mysql
    environment:
      - PMA_HOST=fullstack-mysql # Note the "mysql". Must be the name of the what you used as the mysql service.
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - 9090:80
    restart: always
    networks:
      - fullstack


volumes:
  api:
  database_mysql:                   # Uncomment this when using mysql.

# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    driver: bridge